global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'api-reservas'
    static_configs:
      - targets: ['api:3000']
        labels:
          service: 'api-reservas'
          environment: 'development'
